/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentIdentity {
  export type AgentProfileStruct = {
    walletAddress: AddressLike;
    name: string;
    description: string;
    creatorAddress: string;
    capabilities: string[];
    metadataUri: string;
    verified: boolean;
    registeredAt: BigNumberish;
    reputationScore: BigNumberish;
  };

  export type AgentProfileStructOutput = [
    walletAddress: string,
    name: string,
    description: string,
    creatorAddress: string,
    capabilities: string[],
    metadataUri: string,
    verified: boolean,
    registeredAt: bigint,
    reputationScore: bigint
  ] & {
    walletAddress: string;
    name: string;
    description: string;
    creatorAddress: string;
    capabilities: string[];
    metadataUri: string;
    verified: boolean;
    registeredAt: bigint;
    reputationScore: bigint;
  };
}

export interface AgentIdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkAgent"
      | "getAgent"
      | "getAgentByName"
      | "getAllAgents"
      | "isRegisteredAgent"
      | "owner"
      | "registerAgent"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateAgentReputation"
      | "verifyAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentReputationUpdated"
      | "AgentVerified"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentByName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike, string, string, string, string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgentReputation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAgent",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "checkAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    walletAddress: AddressLike,
    name: string,
    creatorAddress: string
  ];
  export type OutputTuple = [
    walletAddress: string,
    name: string,
    creatorAddress: string
  ];
  export interface OutputObject {
    walletAddress: string;
    name: string;
    creatorAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentReputationUpdatedEvent {
  export type InputTuple = [walletAddress: AddressLike, newScore: BigNumberish];
  export type OutputTuple = [walletAddress: string, newScore: bigint];
  export interface OutputObject {
    walletAddress: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentVerifiedEvent {
  export type InputTuple = [walletAddress: AddressLike, verified: boolean];
  export type OutputTuple = [walletAddress: string, verified: boolean];
  export interface OutputObject {
    walletAddress: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentIdentity extends BaseContract {
  connect(runner?: ContractRunner | null): AgentIdentity;
  waitForDeployment(): Promise<this>;

  interface: AgentIdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAgent: TypedContractMethod<
    [walletAddress: AddressLike],
    [boolean],
    "view"
  >;

  getAgent: TypedContractMethod<
    [walletAddress: AddressLike],
    [AgentIdentity.AgentProfileStructOutput],
    "view"
  >;

  getAgentByName: TypedContractMethod<
    [name: string],
    [AgentIdentity.AgentProfileStructOutput],
    "view"
  >;

  getAllAgents: TypedContractMethod<[], [string[]], "view">;

  isRegisteredAgent: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [
      walletAddress: AddressLike,
      name: string,
      description: string,
      creatorAddress: string,
      capabilities: string[],
      metadataUri: string
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgentReputation: TypedContractMethod<
    [walletAddress: AddressLike, newScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyAgent: TypedContractMethod<
    [walletAddress: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAgent"
  ): TypedContractMethod<[walletAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [walletAddress: AddressLike],
    [AgentIdentity.AgentProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentByName"
  ): TypedContractMethod<
    [name: string],
    [AgentIdentity.AgentProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isRegisteredAgent"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      walletAddress: AddressLike,
      name: string,
      description: string,
      creatorAddress: string,
      capabilities: string[],
      metadataUri: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgentReputation"
  ): TypedContractMethod<
    [walletAddress: AddressLike, newScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAgent"
  ): TypedContractMethod<
    [walletAddress: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentReputationUpdated"
  ): TypedContractEvent<
    AgentReputationUpdatedEvent.InputTuple,
    AgentReputationUpdatedEvent.OutputTuple,
    AgentReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentVerified"
  ): TypedContractEvent<
    AgentVerifiedEvent.InputTuple,
    AgentVerifiedEvent.OutputTuple,
    AgentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,string,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentReputationUpdated(address,uint256)": TypedContractEvent<
      AgentReputationUpdatedEvent.InputTuple,
      AgentReputationUpdatedEvent.OutputTuple,
      AgentReputationUpdatedEvent.OutputObject
    >;
    AgentReputationUpdated: TypedContractEvent<
      AgentReputationUpdatedEvent.InputTuple,
      AgentReputationUpdatedEvent.OutputTuple,
      AgentReputationUpdatedEvent.OutputObject
    >;

    "AgentVerified(address,bool)": TypedContractEvent<
      AgentVerifiedEvent.InputTuple,
      AgentVerifiedEvent.OutputTuple,
      AgentVerifiedEvent.OutputObject
    >;
    AgentVerified: TypedContractEvent<
      AgentVerifiedEvent.InputTuple,
      AgentVerifiedEvent.OutputTuple,
      AgentVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
