/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AttestationRegistry {
  export type AttestationRecordStruct = {
    id: BigNumberish;
    jobId: BigNumberish;
    escrowContract: AddressLike;
    provider: AddressLike;
    verifier: AddressLike;
    attestatonHash: string;
    verified: boolean;
    timestamp: BigNumberish;
    signature: BytesLike;
  };

  export type AttestationRecordStructOutput = [
    id: bigint,
    jobId: bigint,
    escrowContract: string,
    provider: string,
    verifier: string,
    attestatonHash: string,
    verified: boolean,
    timestamp: bigint,
    signature: string
  ] & {
    id: bigint;
    jobId: bigint;
    escrowContract: string;
    provider: string;
    verifier: string;
    attestatonHash: string;
    verified: boolean;
    timestamp: bigint;
    signature: string;
  };

  export type ReputationStruct = {
    completedJobs: BigNumberish;
    successfulAttestations: BigNumberish;
    failedAttestations: BigNumberish;
    reputationScore: BigNumberish;
  };

  export type ReputationStructOutput = [
    completedJobs: bigint,
    successfulAttestations: bigint,
    failedAttestations: bigint,
    reputationScore: bigint
  ] & {
    completedJobs: bigint;
    successfulAttestations: bigint;
    failedAttestations: bigint;
    reputationScore: bigint;
  };
}

export interface AttestationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvedVerifiers"
      | "calculateReputationScore"
      | "createAttestation"
      | "getAttestation"
      | "getProviderAttestations"
      | "getReputation"
      | "owner"
      | "renounceOwnership"
      | "reputations"
      | "setApprovedVerifier"
      | "transferOwnership"
      | "verifyAttestation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationCreated"
      | "AttestationVerified"
      | "OwnershipTransferred"
      | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvedVerifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateReputationScore",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAttestation",
    values: [BigNumberish, AddressLike, AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderAttestations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovedVerifier",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttestation",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "approvedVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateReputationScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovedVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttestation",
    data: BytesLike
  ): Result;
}

export namespace AttestationCreatedEvent {
  export type InputTuple = [
    attestationId: BigNumberish,
    jobId: BigNumberish,
    provider: AddressLike,
    verifier: AddressLike
  ];
  export type OutputTuple = [
    attestationId: bigint,
    jobId: bigint,
    provider: string,
    verifier: string
  ];
  export interface OutputObject {
    attestationId: bigint;
    jobId: bigint;
    provider: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationVerifiedEvent {
  export type InputTuple = [attestationId: BigNumberish, verified: boolean];
  export type OutputTuple = [attestationId: bigint, verified: boolean];
  export interface OutputObject {
    attestationId: bigint;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [provider: AddressLike, newScore: BigNumberish];
  export type OutputTuple = [provider: string, newScore: bigint];
  export interface OutputObject {
    provider: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttestationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvedVerifiers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  calculateReputationScore: TypedContractMethod<
    [completed: BigNumberish, successful: BigNumberish, failed: BigNumberish],
    [bigint],
    "view"
  >;

  createAttestation: TypedContractMethod<
    [
      jobId: BigNumberish,
      escrowContract: AddressLike,
      provider: AddressLike,
      attestatonHash: string,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getAttestation: TypedContractMethod<
    [attestationId: BigNumberish],
    [AttestationRegistry.AttestationRecordStructOutput],
    "view"
  >;

  getProviderAttestations: TypedContractMethod<
    [provider: AddressLike],
    [bigint[]],
    "view"
  >;

  getReputation: TypedContractMethod<
    [provider: AddressLike],
    [AttestationRegistry.ReputationStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        completedJobs: bigint;
        successfulAttestations: bigint;
        failedAttestations: bigint;
        reputationScore: bigint;
      }
    ],
    "view"
  >;

  setApprovedVerifier: TypedContractMethod<
    [verifier: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyAttestation: TypedContractMethod<
    [attestationId: BigNumberish, verified: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvedVerifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "calculateReputationScore"
  ): TypedContractMethod<
    [completed: BigNumberish, successful: BigNumberish, failed: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAttestation"
  ): TypedContractMethod<
    [
      jobId: BigNumberish,
      escrowContract: AddressLike,
      provider: AddressLike,
      attestatonHash: string,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [attestationId: BigNumberish],
    [AttestationRegistry.AttestationRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderAttestations"
  ): TypedContractMethod<[provider: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [provider: AddressLike],
    [AttestationRegistry.ReputationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        completedJobs: bigint;
        successfulAttestations: bigint;
        failedAttestations: bigint;
        reputationScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setApprovedVerifier"
  ): TypedContractMethod<
    [verifier: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyAttestation"
  ): TypedContractMethod<
    [attestationId: BigNumberish, verified: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AttestationCreated"
  ): TypedContractEvent<
    AttestationCreatedEvent.InputTuple,
    AttestationCreatedEvent.OutputTuple,
    AttestationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AttestationVerified"
  ): TypedContractEvent<
    AttestationVerifiedEvent.InputTuple,
    AttestationVerifiedEvent.OutputTuple,
    AttestationVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "AttestationCreated(uint256,uint256,address,address)": TypedContractEvent<
      AttestationCreatedEvent.InputTuple,
      AttestationCreatedEvent.OutputTuple,
      AttestationCreatedEvent.OutputObject
    >;
    AttestationCreated: TypedContractEvent<
      AttestationCreatedEvent.InputTuple,
      AttestationCreatedEvent.OutputTuple,
      AttestationCreatedEvent.OutputObject
    >;

    "AttestationVerified(uint256,bool)": TypedContractEvent<
      AttestationVerifiedEvent.InputTuple,
      AttestationVerifiedEvent.OutputTuple,
      AttestationVerifiedEvent.OutputObject
    >;
    AttestationVerified: TypedContractEvent<
      AttestationVerifiedEvent.InputTuple,
      AttestationVerifiedEvent.OutputTuple,
      AttestationVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
