/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { AgentIdentity } from "./AgentIdentity";
export type { AttestationRegistry } from "./AttestationRegistry";
export type { Escrow } from "./Escrow";
