/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEscrow {
  export type JobStruct = {
    id: BigNumberish;
    client: AddressLike;
    provider: AddressLike;
    description: string;
    deliverableHash: string;
    paymentAmount: BigNumberish;
    paymentToken: AddressLike;
    status: BigNumberish;
    verificationType: BigNumberish;
    createdAt: BigNumberish;
    deadlineAt: BigNumberish;
    metadata: string;
  };

  export type JobStructOutput = [
    id: bigint,
    client: string,
    provider: string,
    description: string,
    deliverableHash: string,
    paymentAmount: bigint,
    paymentToken: string,
    status: bigint,
    verificationType: bigint,
    createdAt: bigint,
    deadlineAt: bigint,
    metadata: string
  ] & {
    id: bigint;
    client: string;
    provider: string;
    description: string;
    deliverableHash: string;
    paymentAmount: bigint;
    paymentToken: string;
    status: bigint;
    verificationType: bigint;
    createdAt: bigint;
    deadlineAt: bigint;
    metadata: string;
  };
}

export interface IEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelJob"
      | "createJob"
      | "getJob"
      | "getJobStatus"
      | "openDispute"
      | "releasePayment"
      | "resolveDispute"
      | "submitWork"
      | "verifyWork"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeOpened"
      | "DisputeResolved"
      | "JobCancelled"
      | "JobCreated"
      | "JobSubmitted"
      | "JobVerified"
      | "PaymentReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [
      AddressLike,
      string,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyWork",
    values: [BigNumberish, boolean, string]
  ): string;

  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyWork", data: BytesLike): Result;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    opener: AddressLike,
    reason: string
  ];
  export type OutputTuple = [jobId: bigint, opener: string, reason: string];
  export interface OutputObject {
    jobId: bigint;
    opener: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    resolver: AddressLike,
    refundedToClient: boolean
  ];
  export type OutputTuple = [
    jobId: bigint,
    resolver: string,
    refundedToClient: boolean
  ];
  export interface OutputObject {
    jobId: bigint;
    resolver: string;
    refundedToClient: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BigNumberish, canceller: AddressLike];
  export type OutputTuple = [jobId: bigint, canceller: string];
  export interface OutputObject {
    jobId: bigint;
    canceller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    provider: AddressLike,
    paymentAmount: BigNumberish,
    paymentToken: AddressLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    provider: string,
    paymentAmount: bigint,
    paymentToken: string
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    provider: string;
    paymentAmount: bigint;
    paymentToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    provider: AddressLike,
    deliverableHash: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    provider: string,
    deliverableHash: string
  ];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
    deliverableHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobVerifiedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    verifier: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    jobId: bigint,
    verifier: string,
    approved: boolean
  ];
  export interface OutputObject {
    jobId: bigint;
    verifier: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    provider: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, provider: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): IEscrow;
  waitForDeployment(): Promise<this>;

  interface: IEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  createJob: TypedContractMethod<
    [
      provider: AddressLike,
      description: string,
      paymentAmount: BigNumberish,
      paymentToken: AddressLike,
      deadline: BigNumberish,
      verificationType: BigNumberish,
      metadata: string
    ],
    [bigint],
    "payable"
  >;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [IEscrow.JobStructOutput],
    "view"
  >;

  getJobStatus: TypedContractMethod<[jobId: BigNumberish], [bigint], "view">;

  openDispute: TypedContractMethod<
    [jobId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  releasePayment: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [jobId: BigNumberish, refundToClient: boolean],
    [void],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<
    [jobId: BigNumberish, deliverableHash: string, attestation: string],
    [void],
    "nonpayable"
  >;

  verifyWork: TypedContractMethod<
    [jobId: BigNumberish, approved: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      provider: AddressLike,
      description: string,
      paymentAmount: BigNumberish,
      paymentToken: AddressLike,
      deadline: BigNumberish,
      verificationType: BigNumberish,
      metadata: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [IEscrow.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobStatus"
  ): TypedContractMethod<[jobId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [jobId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [jobId: BigNumberish, refundToClient: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<
    [jobId: BigNumberish, deliverableHash: string, attestation: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyWork"
  ): TypedContractMethod<
    [jobId: BigNumberish, approved: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobSubmitted"
  ): TypedContractEvent<
    JobSubmittedEvent.InputTuple,
    JobSubmittedEvent.OutputTuple,
    JobSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "JobVerified"
  ): TypedContractEvent<
    JobVerifiedEvent.InputTuple,
    JobVerifiedEvent.OutputTuple,
    JobVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;

  filters: {
    "DisputeOpened(uint256,address,string)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "DisputeResolved(uint256,address,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "JobCancelled(uint256,address)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobCreated(uint256,address,address,uint256,address)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobSubmitted(uint256,address,string)": TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;
    JobSubmitted: TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;

    "JobVerified(uint256,address,bool)": TypedContractEvent<
      JobVerifiedEvent.InputTuple,
      JobVerifiedEvent.OutputTuple,
      JobVerifiedEvent.OutputObject
    >;
    JobVerified: TypedContractEvent<
      JobVerifiedEvent.InputTuple,
      JobVerifiedEvent.OutputTuple,
      JobVerifiedEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
  };
}
